from docx import Document
from io import BytesIO

def generate_docx(content):
    doc = Document()
    
    # Adding a title to the document
    doc.add_heading('Generated by CareerForge AI', 0)
    
    # Cleaning up the markdown for simple docx conversion
    # Simple logic: adding content as paragraphs
    for line in content.split('\n'):
        if line.startswith('# '):
            doc.add_heading(line.replace('# ', ''), level=1)
        elif line.startswith('## '):
            doc.add_heading(line.replace('## ', ''), level=2)
        elif line.startswith('- '):
            doc.add_paragraph(line, style='List Bullet')
        else:
            doc.add_paragraph(line)
            
    bio = BytesIO()
    doc.save(bio)
    return bio.getvalue()